---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgClsFqCw+MTMYCc5dMbXIvg1/5WcuWIV/fzVO0695boxr+CiBApU1X6l1gd/dykElDcTLb2HwoYWAsPqNlZyMYa5ol0efZ4gsxPqnK7BsJa8Cpds8TwMwrLEQwv/zcod5kpIyjQC4u4bvMrAUs79/EqaNvGLmxxnDT/w1eVUyqbQEPouUg+fgLr4zcws40Q5jPyx/p8MVgvYd1gBrjqu6tnE6EtoGzsWUmxxcAUkFg+gpiXk+YiEODy4YoRk3TOjP7Uc2lC7Vv2xMGkzfpS3xTCMiyHrdtJaWoYojIkmQMkjzeqUofPOkazw14TM/88QhflZTCfgZTLjshrCii9FiTxewgpWdnG/L7hUif8G7r4JcE5xG3oN+4m0d1iGvgV8wo67pEuF/f4QNviExOVuqOR8F0cYGhshKe+SWpYggYFXsFA+rj8iLK4qOc/2HCakhkDSa02xq5LDtx6k9BGRyzJHi/2qy9AnbhC3wfnIHm0OYm4X4JuY7ZyFJMh7IZwWja5C4TOhJEXigZL38gSijPwqMhW0g1oRgeLZ7uQ+vz36Pqbp90vNLBZ4waajwDo5GChBQg0/8YHCGcJTCcfgesBJifhXjLH5sMXHghu9yTPUjKWsCt65JfG2KuqFSjPh+N8XeQaRnAgeOPDdBfO7GC/7IULCp1b1yqjEIMwgqFpO9S+GPBk5dJfcwpHwDSs5iuwV1LPaaqZWR7PCJ2nJwG10iM4LXHB2+/KE7L9Xa+TmDqTuR8m2xbDMuMAkUoV8gIsObE9jg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
