---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgADVnnHuuJVHjXX8MauF/bXrtfiZSM6oNgTxTiuaVwz2sxHKFotKswBWUsYI18s/xlVfpeue0HbNCW0YqUhz5GMYtEV8f75HoZ44DGCt2iwD3x/ZcAo7o11hV5Hf65IsV3Dcb+ud/wRgnhVBUuL2PQVIkL404gdTKNYrBNK1cwniBMu3o70a+bRYB01tzQGy7zB3pI0TeMRYYkMo2onK8f0rFUrHGTaqn3NcBecDaA+fstMMUYUFVxzkf/4OnJ4ta7ADQx/ks7uWofU9S3pSK/4+J3mcMMDD7rYZs1fVXUS201vy0TplQlF55ugnRgjCGuklKoQMaTAqazSqKv/3JL33E6DIdM8cEe6B/5sg3beb94dGzwqsL4bu5LSaPpBYp1X70L8p35ZnuLpKcU6NRlBikDKfAnVNWA3oPV4ddmXwArl5rULcW7TGn+f2D2dfauzNQaK8l+cTkTkF1RhpVUuMn49l4quOVk7CcB6EyQP9+sE9N4GP1hvJAdG61gHZ5gtkqxFYImhRnUfftCaiLGTCeqdCXgpYjK358upGvCbqj6w1tkXvhK0BAY88dUPW1OJyBfNNCb07zxkx78Mwm5iuk+/2SYbBr9SXuIBy6rH+kYuMn/G2HKbEmAw9/LYzdnaPWbHiaNzsshkmpwMpK0SE6U6j2kwTSiDVt2Z0OPHV/YVSkaY8kr8oW+Nab+XWJ1o6m9nKxT4UugLoxRiRDeGHWk4tmCiBRgMjVEwviopP0Eiq4pQRm3rcg57r9HwY1xdSejgOlo6NLRPYaiLxG3z7J5nkglUO69qUvT4n1WOB2XxXi5GM8WgUO4hMokKDGmtSMnQiyNQx4Cu4UYVNg75nkRL8MOzyn7RQF+pD7TtPa6OzAQpfyOS0udxOcSMqBOTN/y1u1YZKK92YTbrxgqEHUhQNLuMqJMGQ/OUR58O+cA/KqP2rtva
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
