---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBfnj2uiILnJfCEMPsCjFrOCi1s3WuJqPi0Ru27t6uOglaJdDr5fhbgEEwuI/9TjnbBoUDYxUG0ID9b6W9hRH+Dfp93+wI3LsgaL9awBAqwa+u1VrZJgdXOWXamO2mezutF299WHmx4V57brP2EfAjzZXNs5BJl382YQNn4cZ/N6lI/UeMf/hQNtwX9VY8EqnKRS3OrT4MbgiOABSNhiiZ8enZo6wqxXOv/qTktqYhk94zcufBWj95r7TXqyGXHBNc/80eLo+svYKnf3qna6V8wVJd1hu22K4oSqEwK8z0bQeIFMvXOqFnYVvR3uJGthqz90l/fBevEdzN6Zlncg6V5lnqMMuxG1YDCh1M2lK1Wtz9tc/vIPmuVT3wcr05mVPPsylakfeFTd6SWHBki+OERkbspB/lYUIbr8BNHfiDzpBOH69eoCcm/1ZbQLABDNF49qusFKAxlJ4HuLcZR9TDfM8mLVwd46vgryOE6Mk5iXIS38RFM2werMnxhG+sF8NxXQbELKecJ/+DxVXO1nHSn48MRFBeeFEpQezpL4UBpIT3rhAReN9tQQDkJqUWVGj1CPSykNZoDxWOLeSdt50XnejaWg5SN9MbCuXHPOoA1aem5pAsBiJWDvYCX5L3hHKm2E+Yeq5UGGKwm4pdBpngICK2lIttzou1wm749l/qcvYLVNSrzkz+EOAMp8T2RK9hXZvXbe1hAJ5+TLP6MVuqxOd61YBMhG5w1pxpF2x4YCcgCYf0PdlPB1xZ5l8cfwaLgK3XP5wBaxVh0W7DxtH/u+8EBsiJiUK3wmFLCADNEMlFcpBEylaM3OcDwvOX5dwHr5iyv2Vu67ceJnWx4vkiFJLtoCJ9ymkikcJADNsaB8XLErOqTI8Lk574n2+4f/b1OUbOLx3IOvIUl2EkPvwANiPO8nk3IMCB/y3GSfX+NAh3Q9lmI0cItLZs742iGNOaFoEl6bySwE7hDXHLObHKgF4HULGR3YXmAAfjF9ZAz9yQuS6arP6EZkAQwH2u8RKhVW3aN/7VZCQ==
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
