---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgDK9fguTJcYstoMOFgUnRHPedku2leszl4GkF0IvZ3VUNg5w7UyodEwzCgybKFk78os9Hnvw5kL9XltHNjRYuPswRGaszXaNiMVhvLa3OOAPLFIBGn9BLnXa8LhRbIdthHKcp4d1UJfmvmvkNgvV1uWg00jZD1rPCe3pM/W5Ma8S/4MKu/Cegve++Uvg0E7yMSQqnCQWJn8cmZH1fQpQSB1SZbqR5mMLO2jZ/QYoqW8ZaP/TPfpfLUP03e9m2CqrV0VRpIIQUDICZr0AcLLSyVMyHpYwHnV+nAbuSW1zgFZEYLQk2glx6aiPG4Jp6OsEdUvmgJC5hZRw94y7jCKRX/YYSgOl1//vg8QAyjd8NmNteVa80/1nkn8z9c/a0eQNe6R0uFIqN79xHpRALax4m4AZYM0MLA4bDWK6iVTWIqnABlybcXTV55Td9XlZxxQRMCZdpf1RG2eOGybp9iLHdsbsXIx98IpSfuqBL9uoQu/H4e6zoxx9kzWR9c80nv5oSkSfp09xworMUdpev1zJacJWOQH3U/1dph6JYZW8Ja1ZmGQmc4P3w5/JIWMBCXee9IMhJE1Z0Toxdqua0Aav1QPILxE0/UWcojEdrF/U+mDxxA92VsT1fe825RDPdcGpwSVqN+Z8h+0GLaNBynPSrnrYDcBIsM23MB2yWjhQ1YfnxKZZVFGB8RqV2aQzHTMNd/cuFINvEeX0ti1wfaMFA3Sw6oIrUKDPGCIOoE7E36u+/3c+bDm9kld6ayQZ+hHw0jmEzuNQVX/thnepvca6xB/SKNiRTCrj3c=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argocd
