---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collabora-admin
  namespace: collabora
spec:
  encryptedData:
    password: AgB6E94xc+RO3X24VESF2mugoazLki6bErNdVnRNJzSgeE2Z0WvE0C2qRvkeBpqcdfHdai+fy6RXRmkSE1tv2jHhjE2AF2ZXgrYIDgIb/TbO4QyXC2coE+NHPhHIBYXdx/sGmnFm5Rqyu/j1ud8M69thE1E+2k5wl/zcwbgALYgXZGJ1GPb7uFnBMH/A/h24PABpXT1pOOIMbhUByU8ijhUcjvcmCrjJD4zBxJhq1sExb7MOA4W+XhRDxbp63SQXGjuumJCNQDUaUw/s11MlYVFEqqf+j+5MNDd2IF2+QVPDD0sZlCT7G+2IR82ZCP6kCb52h0k/QrL352KMTUOloOBylvt9KTeA5IruP3kyM9pKcruTV1AF4zjxA7pMmd7aW0FQpvuAKMJc1RJgppTK+OYEJqLko/CeKAZe3yg6Hd84ISB1wR1NKQMZzId/gvFjsB3DgzHAWXnNUQ0RUW0J4+RzOI3jYeYxzsF1aeMWTCvMqADExpOIhV+9t0VjbaHfdFcWYX7qFMSLXwDBsIPyF5aY9cSMuerqdr0H+ZO9D0aANZtnIEM0U9jTtRDdsqGLGlH9GJwLEz+FZp/nNByvN6vJgzKD64cg9eOSmRx028VrPSmB7LWDdWJtR/I07y1Ml9NkErkUQBYhsqzRMpLLiu6Bw7aI8nmpUyRPXLoY+16JuEFzZryVhFPqht2Oy6ZYbpYCa2F6O4O5bsrrly7HwQ==
  template:
    metadata:
      name: collabora-admin
      namespace: collabora
