---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-act-runner
  namespace: gitea
spec:
  encryptedData:
    registration-token: AgB7KMah9sjuRo4Gw74Lej+/cxJDydePYShlJqOqnXDV5q2NclNy3rnBdZlAekjUX6tvggC68izfRDH3qtywj1GXiJE2JPrcP1jOMZLv0sSrLTx3iSfrwfaaUqrTHa6h3JzVvNAh2gr/HMA4SrqlqcaEZL/Prh+vnOCJG47qhzUK+3Y6+SZp5OT4t5HbEAIU3Joj0fWlmGohyorYdmxXYArLhbxS7M4OmvcmnIT9jhoYvLiAk/VjupplROiv0ZnnS3zmstY7vJIHNWRkyVftB4NVymRwkmK6z2agqqe91MWyij/4P+D5yxSiemlbe+9MQJhV8b9J3glEaJWIayhY6OyGAb/YFP9/yeiFGkHdx6MDMwRLF12yfur9qXFkgHD9yCnPu5+uuSJn+IKeONqhnufjqfOwE94Cbw5ts+GGNLrwJZEjZy3dvzF7AM0aR7S4ZNUFwiEgkzb5J4dhHfum3NeHn4/nGitrwlLWalImQu4gBMZV+MpKjKI06t09sAeS4RTQQ0oC1px7oI7DGL7QahHxt+AMxGAeIIYKWusEnxczGwaXjNxE+RC4ha6ICK7DeQlaVmXq4x6EMevuwlIBP8BlNpP4GEoHjPu2Eo5wNZ5FNmr87KI1BIv9jwKYmjOI0vMqhehi7GNuTVzq3AmsuOUeZPpU8Izo6XYGUCBqWms6CgqtotkMx7J7XlkNLeJyCJp9Qe7hn61eSLetC4hkc9h2morBpvwjOsM3YUT5ajXCYlMAVR2h5DXg
  template:
    metadata:
      name: gitea-act-runner
      namespace: gitea
