apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiwix
  namespace: kiwix
spec:
  ingressClassName: traefik
  rules:
    - host: wiki.henrydowd.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiwix-external
                port:
                  number: 8080
    - host: wiki.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiwix-external
                port:
                  number: 8080
