apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "34.x"
    helm:
      values: |
        deployment:
          replicas: 1

        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/loadBalancerIPs: "192.168.1.200"

        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true

        ingressClass:
          enabled: true
          isDefaultClass: true

        logs:
          general:
            level: INFO
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
