---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-oidc
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: AgAHmHE7wQfPAgQYZNjujeMn3cJC7UfbmQENASNlt4Vxva6SeQWXcRfsiUpce2jbRLJXWGZ1lORbVHzixpJGJ1frEp5L/39flOyx1u3dvFUISHZiMCjT+NBYL95mwiu/+njngdrrxccHJ4eWnbjLUs9JsXV7VCz7MEpfcixSjvbpM/pPvouhFNsYZ6LDBG2cQAXgKyMCUkA5Z43yo/tzJkJi/40iOKsfvWsNJhwVH3KPIgkULj5XYS/l2DqWdkq1v0TpZ1pwE602PlnP4/fcqwzQoFjtE56K5aeUnm1GFe5TM6aOtJgQgRY9ZiV+tG2DXiKJdJ30wDrbfc5Dwqnk/tWAVj3CO7cvxb9qGlQuGHqmFWesIXMYfAer0eY8oE3DBklz7Dv18eA6ahIyhvbVugMlXRwQhxeeXivA4jsGqLanyCAVHTPqXBHU2up8U/WipL/1IkqNYd5GiUdi37N/jetx7lgvFb6xzhlQAP16dxd9Exbcf1FmPa5H3Wl9k/z83ZnosPTTXwqiiwQaKDj4Ehr4wzZ85166yVptV6uyazYwOVP9kPC9RUAcE48ddXcKpi2fKfHRXtNNOYe5SfHjw+ytfDgzc1L7/hy64gwacG+9sMhJoPvCndxrn3uTqFP/qyG2l6WLHOs/EL5u11gh1KZ0ARMW1H0v0LUUDnpjf0uBx1LCTNIAOI/wju22Xcwq2Hu3fqUoFt5vaswED3i0o4xjLi+CN/w5sC9D2XsnZvkRxMEcKKXU4693S9DgjTldAGS/ujzS8vxv2VP/7MtzgzVzLUNGTgyLFGwq/2C/WGB/Abr4NrQxBlKtE0BNcQcIDoZavgsQprazTgiyIChqVnUBlwEPF7Y2feq7jC4H9mPP2MZSGQ3ram+/VopdWL0J09Ix491tm5X9M4g/W7Z7P+F9WYyz8qyEMmk9RcKASuFekOYVudFPKg1FvivUEBhAJSwIcpvbhZ0kYjcgb7Pu4e8dHVcTOVXYU/CbceOcmV6Kgh1kkeXTg6WZDhr1wGQZj5FczTmPf4Qkq0H7OoSHi85aeK3CpAAR6Ql4bBkttwJ2UCbeAh3O2ZUweyDnvtdiJdaLYlgIihUDKaNP11StiLsy7po9fE+Fb5dDi9Kq1WmY+Qg/VsFvuFN1ddODQg+i/oOwWw==
  template:
    metadata:
      name: paperless-oidc
      namespace: paperless
