---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgA+AVeb/6I7jsuSumbCqEIKqAwA3OUHJ3vb8U5FxbDenPypcP6XiWP0yHlza1sFVyLROsX/NZPcwyjuEe+c3EMPw/0dXsoEIRNvTaWXXKQAvd6Rqi1nvatzIqfJspYD9aMrrtZsRBBKYvfkEm0EDIYhi96R1YOua+8SwrRzx9LL7x0LAJdxOSXzmS7FzbniNzR+ORD5OtYl57K9xTy6F818RcBd9KKn13YsouuNAsmdMDtrrBXBiJni54vlQzvCTIJhutySOHTWasVDyqGyjh4Ykav6R3DU/L7yqZBSISwIycJemUuY24/s8n23WAz8gdLiCZL3FGssk0z7ismcMXTIXLzHas2G84torpDM8FAcVgOVbALNKbabC7j46Za77XWlJuGAhaHg8YjJlJS87nKZMTmtqMecLk3Tzy5G+CLfP3RK/vTS6IszkQaxM0PSP4CzOK7fqDQFdevSciFq1VA0mfZAMKKEUkCgNKxK6anIoqaJIwst6Niv47W8hqZZvjVIjsTdwN8rh9LMuoaGT8c7FS++7f1Nv6yoDnZrUSvJ6wHz/ydO7xycfVKbmMq2ESsUQFtAdj/UtrBLoRau6WkCWGNHUkqxKhydLkAkgcaU+iHfyRLYlXxT3z1U2rZfjAtZz/e+cVXBrUY0Y5AzALLsidPNBofZ7waHCWxV86WQG/fwyhJZLEdMvYaEDjDLTxCEqHVRs4TZAXx1uLotaKRJtrWjJr+rpvaGVBf5dTncvQ==
  template:
    metadata:
      name: immich-secrets
      namespace: immich
    type: Opaque
