---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCVOQKwshjHwYY7GwBJWIdX0kAZJT8DQSg9s8E4JJcNQl76N2bmmFNVD+yTwnvokaI3bcCdZxGUJrmEjFx76HU490kl3GPAwtYOr01jdRHw0mfN56H9r+iov5PmYF2zrF2Tio98wH9BkHChJuISaJC47mIJuVXH5M3kXBHPZTKqrQzhac0xvPVCpMQ8b8vKMg3TzoWLXLmdlwUrGO9L645Neu0eT7MEW4rTwoB2hnRSDQN3TzEexwZ0m0dbKRulZUfDKUw37Oodi/FeeP+5gB7bL5cllHgEbZ9RXpL6ncsaOUeH0JqOcbwBJCCJzsc+qloe+l7oQqqbDhEXJp/AqAVhbVo/0KBkyf8tB+E3qp/0Xzk966hd9l6X5S8YGwRAFqYQZxyjC5NA0zeuHdDRI+akIL6rKmTfHICMMydKG/q4vBVhHVvAo4tjJ6Dg//rv4JnxVbZsG2APvznnZXm5B+kpkFFzd2F1xMaE6os9aJvhcJnN8STN7s+FpfOcAHSr1eud3VS3mwJSt8Slmu+33Pa3pcuXPPLBlCuQ5Mf/3LnC4Pg4y0GbowP1ZF8roUZ7+b5mVd+q4b7kPATcf/NJ8tlHlZN0gnftsj9PcgrbPlZBiBE9LLIa4xwzKInrAFp2FYAuyxm5SdcsrjUHe9AlZayRkTL3TCk226v5Hb5QguT5D+6VrIZhHs9BTuJv534qM+tsN6q/AJdy7XCsiXtB/w==
    admin-user: AgCYkH9zFFWNjBDtwNo8+5LcnaU6DaFjoagUApXxbDO6WkivlnWjg9nhxu7CJ40IyzcFopr8ojUc2Rm8QB5o9tVBXrO42NOZ2vFm1Ds+k9BlGNgQULtySAO1wWpnQS86SMUV8k8b6/AfgT9cuPpIn0M4/QTzXuGoV+QqKZTnL5xIkh1Dc2gfTv533Eob8elHR6wGX97x//xvl3afizXkczOZFaJl83ez4zzvKmfUgIepDatZgdGbzXw2dyhtemXxuYwmS8hpC7lsYrzhl/D3jx1Muwa4vu/0gNms4yIhj2TFOBgWSliiLXOQWVUY/6LABH9JAjYPRc95KiUaEiozw/9PD55C1zJOQ3JeeJ4KfIOMSJ1QOwUzzZ9JGUfXNVjpdOe4BlqWBveMEh4K3pYbJbH6WPwopc5YmvJiUkEoAviCDf/aSxEh3GTKs9pQ+qjwIXkpccBkkC8M6AtXWcc2oDmuCrumu1ldwW/uTU+c2qOqwOHd+aE6oWd2ayfC3Q9T8G3wfAsx9D/UzdAQ5YBMLTBGxDNQ5USSy2nwWfp7UbZ63E4kCl7BXfZnedsZVC82GMAXLleQFr3XDw3Fk5Ow1hZhln/TfgME8cyLTP92bNV4XBOuXEj+1T+cruThMS1G6zrHSxjuKN6m7xX1j/hIu2mAKJKso+B0FPD7W6V9KJFZdc/17P8c/JCbx+nSlnqe8Ldq4MnKJA==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
