---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgCDvXCG4j2bdCLin+eZM23chHsfU7pJKhG77Aa0ZFU2IsEmxSS1/AiK3heUyJZgW6950RdXq8Q+aQR8Wab/bIYxdHZoaQtp8GNJdcBny9Z/IppUS4ZQD8/5bea50st+uDkrGUDHoFQ+u0ZnjfSHA5asrhWDhCgiKtQCFZGBeuzgz+VKn/lJti4sm5SKwNQrVSXy7VBqEJVf99ayyHjGICssJ1wpOmTODhHJb1rzjNOd6Zb159G3GWh79hUDlbngVXqdyd3riNqhLiqp0OWWKgrRhrTSZ6EgxCTjvZszWrZ+q9J4zUfFyVevXpVl5GX/4pVhqOo4ocMjr0yENMBNihAKXi7SA7wG5SgQHM4freTXhALa9tuDB2W/54FyAmmfxYOBbwSSQYwyoGKHdSejZFcW3oqQ4/3DhmnW0TIEWG4zyIrxCn7DFBehEQBisW/nj3UKjbHtRZxpCL4CyNIZv63jQRCI0BcIAfbRx+blZ1plbXwOnIk/DqAF7kldVIBGGyRrKC0h+iM687qgmijfl1aAQ8AJE8N1CaPuNdXnAevknakO3m6zrSzu1Hg1pzxSOYMx9Bw2OYc67Jhma1odihGKTSzkSVsOps3b2ZKa7ZdMTx2VhJLbi5f6Ah505nwpRBlQH0IsrYpVZE7D9IxhyzU/iU81fEEP5VMDScIyNYh0Z+loZu+9bMmODbX8OemXxdCoCPM7+IfRLFakchrBajxCR45TsFobXsHrvWE4XnqrKO6u3x0P9LKiTCk3ZHSTqwxv4kpuwHZ54JtDPVmJ1yNYC4YWUzElf1M=
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
