---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-pushover
  namespace: monitoring
spec:
  encryptedData:
    token: AgAfN9gVg5dbqQnJWr4bD0QLnqBgMx2xalZtxdItTTWHvpebGEojJ4iaxsD/kDR0eRSKMvNnMMlE10sSJtfz+yxZGwk+mL15VW+tumJwPhk3vXOH9PSpNxjhsV+QnBYcSMg9QnSpxVfxc0iAY0K5LkASkaJaW1MWu4qhx1R7nvldDb31Dl3Vt3smfs0Ma+yXzrBcx/QBlYblPyqFy57Q4BRNjWqgq/KS3lEYyjWkJyi+IHQuf3iGQUQ9HUfm5q2D4S8GTW99CbpNYAZwW5thPbQG7AGz4OZn1zh4hpoYThM7esAqLvtqfxOn4AjcwPiN4xs+p7zpb3k/PfTABPIF97xN3bF0QxeC8VtVH4gKTrMOHxDQKOAdLDqE5q1s6s+nLY8knqhIMPCFEivKO5tFx3II2FeVJGDmItAs5BPbHU2Cb8q/vZHBvUkh+KV5/48Ihe4YW82Cc7Bt093apZKvi/nvAfmOGuVXLCxSnfw0Dq2CgDYi8VFkRrfddMJGYSyKCuT33AS57DKCJKfzHtmh6TNMwi7HbkuhjD0+7hpynq15/EiNyId799OYCI5WJPe9LkIMds0aT0vvlQEIjt87GEUEYDqWjy/ceKi8gV1T+I6o/WgRc7S63KVdPDX/lBuove1TD6seVu4TAmFtgZT94rXh3cD60vOL/++yr0s6h6/sR2rR5xJGtzOmPwhzxpLZNzTT/hHop3uF+xIqmARoAXaGZ75fK/JWJeaceT+CLhA=
    user_key: AgAIi6q3TlMofxoUFf9DpVNWnKbGQhWOT7UrMf9RGiGg/XnVZeTz/B8b/jborlJL3d5pZv/umao0OT0jnbx8pvkk1tR/eRK1GFQF0KFBbTm/4eWmviiBNX9Vjnljn519LEeLSKYLyabWwE7sn264Xq8CZFxWCYV0tZwshYf90vMVqClwOwvaXqwH28N7K8HbNRgRyOladxX1J99DgKGASkUZWJZQgvBd44n6CKCTWKMZabBRYj8ydA1YhkfmDMzY4/i2OSdQ3YuZeR0o3m/vPfLYg3KElXJtxsDhTVnZtFPL53wFeBzpHBSgvz8Dj+m0b8GWeGNer9hUAfZLJzYkRLhkhMqbsXdkjiOcVXtdjrTAt/IweJPtwFFvWNYj88nSb2zs93xK3jhy2Fs/2AEA0U8M1XDYtqU4LBKthw4Hg7KYGcZE7MNCsfJDbA9ump9Ccjs1k521D2NpPHDY5nl6xT3hyEj46xm9AORqDCFxtgdWh7AG+yWC2AxTQw3yD17TcP6Rq5b/+PgIz/Y9YdKXqTec8E8A5ljtTrRdmaaOM952FZb9p2w43umrUm2WhECOuUfzwELqs8oqWNY5inx1z5bvooA6AIThILgQIBPqQAAZcWsuYxVCmL3Dt4w0hIe/5kwlNzHV6f5uDRzM+eGgtEpbUoEUITwL6T2Uf4PBHcxQUZVWmHjQk8r76G2tCHEyic9fE8t5cyacGm7v4rTcpfll/NpIByc5wX5P0aGoA14=
  template:
    metadata:
      name: alertmanager-pushover
      namespace: monitoring
