---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    smtp_password: AgBL6Ul1AQ94AxTQ37VxWs26Ylgc6y2Vk6gGjQeUAvFEpW8Yk2rKLGuLQX1Rn4AS4BxnLY6XXYnoMEHWgCtEFO5gFssz3EIrwjkIxJ+nhpPBSwxf9ueGESPighHO0fJQVX6T/HAhwp8Ww7J/+mmEm3g0kV6o/VPXDzBQmsRt4NeccxmTl/lQojGsB37dNfTrULuIq/xf8QCsNO5VFr+ISi/JOrPlKYee/+/TuoLeW6W6KAYGKLspLKPbjrJQMVH+5FHpeK/TccvHSQrPGQcw/jdSm2xAS9WlxehlMWfKHx5l41yXfSD+kdKySjjAhvWCigtrKect/qH9VztyR8jkCUDrIRs7MK+ECDIQcUeRQgncOh/8StKmDZR2t13vO9R8k/B52vf8SmEFmsM8jcydYzPoS81xMvGndrVZjhES3PkIGYtGWUqbvU/HwegB62MRPTLrpA4BC8scWv6bJ4c737OtMMC9W39/GP2DvNGDpR3jBBYWBUoZ2AXMDtapJ3doY5VpACIBWEjE3kV7o4lTzf7S2DV8lIr/2R6KG61C2sElWTlZRMIHy1WmGcqyaxC7k7jtZLrL8jUBe1p5v0AerBh72QdkdvrN8U2yjau3rtRGRBpf7w9X0ZCnPg+V4UpiHCFMdEr6QvTstzNu+5EmNYcttrWmoq3PF8IOOwVkVXUIZIoDxXKavV4FxwgUzovmhc8Wzr6W+mTzdr7QHkt5DePXKUWm7h1HVL+Ld5lxFznmBYV219ld/Qvg7w/suQWcQNlQ4K93b85P3ZgTrTO4ly9aRLWbe+57oBaSJxjW+gL5+t+07SIDgJEA7Ho=
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
