#!/usr/bin/env bash
# Step 5a of docs/plans/phase-8-authelia.md: generate Authelia's OIDC provider
# secrets and seal them into this repo.
#
# Produces ONE file, safe to commit:
#   k8s/apps/authelia/sealed-oidc.yaml   -> Secret authelia-oidc, key oidc.yml
#
# WHY A SECOND CONFIG FILE RATHER THAN MORE ENV VARS. The other four Authelia
# secrets arrive as AUTHELIA_*_FILE env vars, but the jwks *private key* cannot:
# it is a structured list entry (key_id/algorithm/use/key), not a scalar, so
# there is no env var that can carry it. Authelia deep-merges multiple --config
# files, so the key lives in its own file mounted from this SealedSecret and the
# deployment passes `--config /secrets/oidc/oidc.yml` after the ConfigMap.
#
# Verified against 4.39.20, and it is worth knowing HOW, because a shallow merge
# here would silently drop every client registration: with a deliberately
# invalid client in the ConfigMap half and the jwks in this half,
# validate-config reports the client error and NOT "jwks is required" — so both
# halves of identity_providers.oidc are live at once. Re-run that check after an
# image bump before trusting the split.
#
# hmac_secret rides in the same file. It could have been an env var, but one
# secret, one mount and one file beats two of each, and a file is not visible in
# `kubectl describe pod` — the same reasoning as seal-secrets.sh.
#
# Not idempotent by design. Rotating the jwks key invalidates every ID token and
# every OIDC consent already granted; rotating hmac_secret invalidates
# authorization codes in flight. Refuses to overwrite unless you pass --force.
set -euo pipefail

cd "$(dirname "$0")"
FORCE="${1:-}"

# Same image the pod runs, so the key format and CLI flags are the ones that
# version ships. Read from deployment.yaml rather than retyped.
IMAGE="$(sed -n 's|^ *image: \(docker.io/authelia/authelia:.*\)$|\1|p' deployment.yaml | head -1)"
[ -n "$IMAGE" ] || { echo "could not read the image tag out of deployment.yaml" >&2; exit 1; }
echo "Using $IMAGE (read from deployment.yaml)"

for c in kubectl kubeseal docker; do
  command -v "$c" >/dev/null || { echo "missing required command: $c" >&2; exit 1; }
done

if [ "$FORCE" != "--force" ] && [ -e sealed-oidc.yaml ]; then
  echo "sealed-oidc.yaml already exists. Re-running rotates the jwks key, which invalidates every issued ID token and every consent already granted. Pass --force if that is really what you want." >&2
  exit 1
fi

# If this cert is unexpected, STOP: sealing against a fresh controller key
# produces a file nothing in the cluster can decrypt.
kubeseal --fetch-cert >/dev/null || { echo "cannot reach the sealed-secrets controller" >&2; exit 1; }
echo "Sealed Secrets controller reachable."

# Rootless docker maps container root to this user, so a 0700 mktemp dir is
# writable by the container and the generated key lands owned by us at 0600.
# Do NOT add `-u $(id -u)` to the docker calls: that maps into an unprivileged
# subuid instead and the key generation fails with EACCES.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
chmod 700 "$TMP"

echo "Generating the RSA-4096 jwks issuer key (slow)..."
docker run --rm -v "$TMP:/keys" "$IMAGE" \
  authelia crypto pair rsa generate --bits 4096 --directory /keys >/dev/null
[ -s "$TMP/private.pem" ] || { echo "jwks key generation failed" >&2; exit 1; }

echo "Generating hmac_secret..."
docker run --rm "$IMAGE" authelia crypto rand --length 64 --charset alphanumeric \
  | sed -n 's/^Random Value: //p' | tr -d '\n' > "$TMP/hmac"
[ "$(wc -c < "$TMP/hmac")" -eq 64 ] || { echo "hmac generation failed" >&2; exit 1; }

# Indented to sit under `key: |`. The block scalar keeps the PEM's newlines.
{
  echo "# Generated by seal-oidc.sh. Merged with the ConfigMap's"
  echo "# identity_providers.oidc.clients at startup via a second --config flag."
  echo "identity_providers:"
  echo "  oidc:"
  echo "    hmac_secret: '$(cat "$TMP/hmac")'"
  echo "    jwks:"
  echo "      - key_id: 'main'"
  echo "        algorithm: 'RS256'"
  echo "        use: 'sig'"
  echo "        key: |"
  sed 's/^/          /' "$TMP/private.pem"
} > "$TMP/oidc.yml"

echo "Sealing..."
kubectl create secret generic authelia-oidc --namespace authelia \
  --from-file=oidc.yml="$TMP/oidc.yml" \
  --dry-run=client -o yaml \
  | kubeseal --controller-name sealed-secrets-controller \
      --controller-namespace kube-system -o yaml > sealed-oidc.yaml

echo
echo "Wrote sealed-oidc.yaml (safe to commit)."
echo
echo "=============================================================="
echo " COPY THIS INTO THE PASSWORD MANAGER NOW. It is not"
echo " recoverable from the sealed file."
echo
echo " Losing it is not fatal the way storage_encryption_key is:"
echo " re-running this script mints a new provider identity. The"
echo " cost is that every OIDC client is logged out and every"
echo " consent is re-prompted, so keep it anyway."
echo "=============================================================="
echo "  hmac_secret: $(cat "$TMP/hmac")"
echo "  jwks private key (RSA-4096, PEM):"
sed 's/^/    /' "$TMP/private.pem"
echo "=============================================================="
