---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users.yml: AgCGMbBlbhxn8ToQ6Ll2gGlMkssadcQLYsxjCVx0nKlINed3247yZ/qKoRGTOJ+XrYr77SFrhlvodY2qBYnNMpDiwNpYEX6ub2sfSaWVr4Z8KGx6RMmuODIBwDmupqf/IPCPDpV14iuyUUTBTt94BLUQOSX2cfcP8dk3Fwhv+fpXLcpPp+Tv+0Zepq+1eBf2rCy8QqiBe3KNt19Ol1282t+ck0uwXiqNo+uKbgLEGDKvkhQxxj3p0og2DQJ6P9lHX06bgLAqK/cW9APhvD4HhF7JH8sSC0pXGcYk+LAMHuyMeYQX6KY/H7x2LnHut6W5Xwb+tBV0jimaH8bKaXqHG3DKlWRi02zFhrN1i6EPyf0YR7mgIAGBfbwxkHiaSzA+Upn7/wKgDk2IQMiqYQW/riZLWzSyPpsJTy13ZoSQ33V8zciNxPuebjYrulcpShustNKdVmnACgvwW+sXzu71ELJ7aokbRyll4YlfQ/AFPQftR1FzzMls9q4EgpHr6bP+PImqjxVJYm9KySp6lNYKEDBwariyHX6IFXfYFD9ASfyN2G448INBpmdtNLGg+4BbZL2h6ljtszQNB3Pz+VGe/HxokbVbTAuXdFYeKz53msloQlO1GGaG5pIa8nuegb4seclplBTviNgN6o1J78OZpjNPAJhYHnYth6HRPNUJqd3q+Nnd6/kVlubn5tJH3hZE1jSW8pbvC4nR4aDycU+kmuAwHAfL4GhbkuwNStAJyEp1Ttdn34GtmxlC9amBrMeT+QIib6a5uVYOMfPjZR2Uo2ICmm/xzqcG87TEpUBh8SPH2ZlbXpcJMnf3qbdPySg7gPH3bsfbCc8+a2+Qn9H4lEs42R4kRv9Rm0iVM8Vfk00krSetTvCviztCgc5OlY1I3nl14nn5kVvGYyhdwUR3FYkeWggQX0qe8l+JQkGwKvBGhuQDuomxcAyuH/RpOtyB+kxVNrv1mm0ioI8ooDgZ8ZSo6Xvt9Wcf1wwfnvhEZaPRWLTuPw==
  template:
    metadata:
      name: authelia-users
      namespace: authelia
